### PR TITLE
PowerSearch and duration for find

### PR DESCRIPTION
**Pull request by mattheuslee**
Part of #167

### CODE REVIEW

**Comment by mattheuslee** [comment]
@CS2103JUN2017-T2/developers 
Please have a look over the changes that I've made, mainly to the Model API and how you update the filtered lists, let me know if you see anything wrong or anything that can be added to provide extra functionality.

Currently the code still functions mostly the same way as last time, but now it has the added options of a OR, POWER_AND and POWER_OR search in case the regular AND search doesn't give any results. I'm still working on improving the PowerMatch section to improve the efficiency and to stop it from going all the way and giving us too many results.

Also, I haven't managed to get around to implementing the date portions of all the "find" type commands, so I was hoping that I could get some help on this since it's quite a lot of changes that need to be made. But basically it involves adding date parsing to the parser, and also passing the dates on to the model as part of the predicate. You can reference how it's done in the list command.

**Review by kevinLamKB — APPROVED** [review]

**Comment by kevinLamKB** [comment]
ok, so basically put 2 more extra null,null parameters when using the updateFilteredList methods yeah? i'll make the necessary changes to saving prevSearch after you've merged this one

**Comment by mattheuslee** [comment]
The two nulls are for the start and end date. since currently most commands don't have the date parser incorporated yet, so it's null, null. Once the parsers are in those should be the start date and end date (which could be null, the predicate qualifier will handle accordingly). I've already made some changes to saving the previous search to accommodate this, see if it needs anything more.

**Review by ChuaPingChan — APPROVED** [review]

**Comment by kevinLamKB** [comment]
ah ok, i missed that update on the previous search. 👍 ok then.
anyway there is a parseDate(String rawdate) method in logic.ParserUtil that find parser can make use of, most of the remaining work will be updating passing of dates to model then

**Review by akd13 — APPROVED** [review]

**Pull request merged**
