### PR TITLE
Fix GUI tests

### PR DESCRIPTION
**Pull request by mattheuslee**
@kevinLamKB Let me know when your logic tests are fixed, then I can pull them into my branch to check everything with travis at one go.

### CODE REVIEW

**Review by ChuaPingChan — APPROVED** [review]

**Comment by kevinLamKB** [comment]
@mattheuslee fixed, i just pushed to logictest_refinement branch

**Comment by mattheuslee** [comment]
Hmm I don't understand why travis can't find the package testutil

**Comment by kevinLamKB** [comment]
now its building fine. thats odd indeed

**Comment by mattheuslee** [comment]
The issue was that on eclipse MainApp could access a class in the /test folder structure, but somehow travis doesn't allow that. So MainApp can only access classes within the /main folder structure

**Comment by mattheuslee** [comment]
YAS IT WORKS

**Comment by kevinLamKB** [comment]
👍 👍 👍

**Pull request merged**
