### PR TITLE
Introduce separate list UI elements for each type of entry

### PR DESCRIPTION
**Pull request by mattheuslee**
* Separate lists by type of entry
* Different CSS colour schemes for each list
* Different CSS colour schemes for current/future entries and overdue entries

### CODE REVIEW

**Comment by mattheuslee** [comment]
Fixing https://github.com/CS2103JUN2017-T2/main/issues/43

**Review by kevinLamKB — APPROVED** [review]
Looks really nice, thanks mattheus.
btw, i noticed theres an OK and a ./data/entrybook.xml at the bottommost panel of the app, below command line. what path is that showing? is it supposed to be path of the human editable datafile we are saving to?

**Comment by mattheuslee** [comment]
Yup it's the path to the datafile with all the saved entries. Bottom left is supposed to show the last modified/saved time, I'll have to check why it's only showing OK.

**Comment by mattheuslee** [comment]
Fix https://github.com/CS2103JUN2017-T2/main/issues/48

**Review by ChuaPingChan — APPROVED** [review]

**Pull request merged**
