### PR TITLE
Modify Model Architecture

### PR DESCRIPTION
**Pull request by ChuaPingChan**
@CS2103JUN2017-T2/developers 
Not ready to merge. Please have a look and provide opinions if you can think of better architecture. Thanks!

### CODE REVIEW

**Review by kevinLamKB — APPROVED** [review]
I looked through, looks good to me.
Do you have an idea why in the original Model, ModelManager, UserPref has a filled box compared to the rest? i tried to flip thru lecture notes and google but didnt find an answer

**Review by mattheuslee — APPROVED** [review]
looks good

**Comment by ChuaPingChan** [comment]
@CS2103JUN2017-T2/developers 
New interfaces like `ReadOnlyFloatingTask`, `ReadOnlyEvent` and `ReadOnlyDeadline` are also necessary for your components right? Because `ReadOnlyEntry` will not have getter methods for `*DateAndTime`.

**Comment by mattheuslee** [comment]
@ChuaPingChan does that mean that if I have
<code>
ReadOnlyEntry entry = new Event(.....);
</code>
then in order for me to use it like an event I should do this:
<code>
ReadOnlyEvent event = entry;
</code>
so I can do
<code>
event.getStartDateAndTime(); // if your call is named in this way
</code>
?

**Comment by ChuaPingChan** [comment]
@mattheuslee 
Yes, or you can right up do
`ReadOnlyEvent event = new Event(...);`
if you already know it's going to be an event at the time you instantiate it.

Do tell me if you can come up with neater architecture though!

**Comment by ChuaPingChan** [comment]
@mattheuslee 
I got a new idea of only sticking with `ReadOnlyEntry`. It goes like this:
When someone wants to do `ReadOnlyEntry.getStartDateAndTime()`, then `ReadOnlyEntry` will check the real type using the `instanceof` keyword and if it finds that the object it's referencing is really an `event`, it'll go ahead with invoking the `getStartDateAndTime()` method on the object. What do you think?

Seems neater to me.

**Comment by mattheuslee** [comment]
@ChuaPingChan Yeah that probably would be good, and then you can throw an exception if `getStartDateAndTime()` is called on something that is actually an floating task. Since for my UI layout I use quite a bit of inheritance to avoid code reuse, so being able to call all the methods directly from ReadOnlyEntry would be great.

**Comment by mattheuslee** [comment]
@ChuaPingChan Does that violate liskov though?

**Comment by kevinLamKB** [comment]
How about this design as an alternative instead of throwing exceptions: all 3 implement ReadOnlyEntry, and getStartDateAndTime() returns null for floating tasks, but works normally for events, deadlines. this way we can implement the sort easier by just using this getter on a ReadOnlyEntry and abusing polymorphism.

**Comment by ChuaPingChan** [comment]
@mattheuslee 
Hmm I'm not sure is it violating Liskov.

My current thinking is that there is a slight difference between this and the example shown by Prof Cristina. In our case, the pre-conditions statements and type-checks will be made in the superclass's interface.
In the example given by Prof Cristina, the subclass impose more stringent restrictions when overriding superclass methods but without changing the superclass, so users of the superclass won't know it cuz it's not stated in the superclass.

What's your view? I'll look up a bit on Google regarding this.

**Comment by ChuaPingChan** [comment]
@CS2103JUN2017-T2/developers 
What do the rest think of @kevinLamKB 's proposal? That will mean instead of throwing exceptions,
1. `ReadOnlyEntry.getStartDateAndTime()` returns `null` for `Deadlines` and `FloatingTask`;
2. and `ReadOnlyEntry.getEndDateAndTime()` returns `null` for `FloatingTask`

**Comment by kevinLamKB** [comment]
oops, i accidently clicked on delete instead of edit. but anyway, my idea is as @ChuaPingChan says.

**Comment by ChuaPingChan** [comment]
@kevinLamKB 
I forgot what's the reason. Why do you prefer getting `null` instead of an exception again?

**Comment by kevinLamKB** [comment]
mainly for sorting reasons. i expect it should be easier to do the sort by date if we arent throwing exceptions everywhere.

also, instead of doing an instanceof kind of check, we can then use Object.requireNonNull method to throw the exception

**Comment by ChuaPingChan** [comment]
@kevinLamKB 
Noted. I'll do that during implementation, thanks.

**Comment by ChuaPingChan** [comment]
@CS2103JUN2017-T2/developers 
I'll merge this tonight if everyone is okay with it (so that I can delete the irritatingly-long-named branch) and implement the classes tomorrow.

**Review by mattheuslee — APPROVED** [review]
good to go on the return null instead of throw exception idea as well.

**Pull request merged**
