### PR TITLE
V0.0 ChuaPingChan - Change '/index' flag.

### PR DESCRIPTION
**Pull request by ChuaPingChan**

### CODE REVIEW

**Comment by ChuaPingChan** [comment]
Note that the "file changed" number shows 2 but the Developer Guide shows 0 lines changed to the content. This is probably because a different hashcode is generated after I resolve the merge conflict when merging V0.0 into V0.0_pingchan.

**Comment by kevinLamKB** [comment]
I'm merging this so i have one central V0.0 to branch off from and do my standardization

**Comment by mattheuslee** [comment]
Did we decide to remove /force since everything can be undone?

**Comment by kevinLamKB** [comment]
Yes, we did. i'll enforce that with my standardization

**Pull request merged**
