### PR TITLE
Model: Resolve TODOs, CheckStyle Warnings, Code Clean-up

### PR DESCRIPTION
**Pull request by ChuaPingChan**
Part of #238 
Part of #237 
Part of #151 
Part of #257

### CODE REVIEW

**Review by mattheuslee — APPROVED** [review]

**Comment by ChuaPingChan** [comment]
Don't quite get coveralls... I only removed unnecessary collate tags and it jumped from +0.5% to -0.05%.

**Review by kevinLamKB — APPROVED** [review]

**Comment by ChuaPingChan** [comment]
@mattheuslee 
Do you know why `ErrorDialogGuiTest` is passing on **continuous-integration/travis-ci/pr** but not on **continuous-integration/travis-ci/push**?

**Comment by mattheuslee** [comment]
That particular test seems to be 50/50 whether it works or not. If you go see the readout for the **continuous-integration/travis-ci/push** test it actually passed the second time around, except travis ran out of time.

**Comment by ChuaPingChan** [comment]
@mattheuslee 
I see, wow, first time happening to me. How do you think we should resolve it? Might cause problems since the module wants us to pass Travis.

**Comment by mattheuslee** [comment]
Should still be okay, we can manually look at the travis output in the meantime. For our final release we just need to make sure the very last commit passes travis, then we're fine.

**Comment by ChuaPingChan** [comment]
Ok I'm resolving the conflicts and merging this then.

**Pull request merged**
