### PR TITLE
Main app tests

### PR DESCRIPTION
**Pull request by akd13**
@mattheuslee If you can create a stub for XmlEntryBookStorage (check StorageManagerTest) it would be better, but this one works fine.

I just realized it'll be very hard to test for IOException in the initModelManager, might get build error in AppVeyor

### CODE REVIEW

**Comment by mattheuslee** [comment]
@akd13 okay, I'll take over from here

**Comment by mattheuslee** [comment]
@CS2103JUN2017-T2/developers Not sure how to test the rest of MainApp, open to suggestions

**Review by ChuaPingChan — APPROVED** [review]

**Comment by akd13** [comment]
@mattheuslee aah much easier to understand now how test stubs work lol. thanks! you can delete my method and collation tag!

**Comment by mattheuslee** [comment]
@akd13 It's alright, I can just leave it in 😄

**Pull request merged**
