### PR TITLE
V0.4 Alert message to user when new added event overlaps with existing events.

### PR DESCRIPTION
**Pull request by ChuaPingChan**
Part of #158

### CODE REVIEW

**Comment by ChuaPingChan** [comment]
Just found a bug, fixing it.

**Comment by ChuaPingChan** [comment]
For now the user will be notified if a newly added event overlaps with existing events. But there will still be no notification for the case when edit/restore results in event overlaps, I'm close to finishing those but I need some time to fix a bug. We can merge this first, I'll create a separate PR for that.

**Review by mattheuslee — APPROVED** [review]
Thanks for correcting my formatting mistakes

**Review by akd13 — APPROVED** [review]

**Review by kevinLamKB — APPROVED** [review]

**Comment by kevinLamKB** [comment]
ah, im touched ModelManager.updateEntry to implement my edit allowing entries to jump between float/deadline/event. i hope not too many merge conflict

**Comment by ChuaPingChan** [comment]
@kevinLamKB 
haha I believe you'll be able to resolve them perfectly 😛

**Pull request merged**
