### PR TITLE
V0.0 ChuaPingChan

### PR DESCRIPTION
**Pull request by ChuaPingChan**

### CODE REVIEW

**Comment by mattheuslee** [comment]
Perhaps for "undo" we should say that it's an unintended command, and not a wrong command, since a wrong command shouldn't be executed (wrong due to syntax error, no entry found etc.).

**Comment by ChuaPingChan** [comment]
@mattheuslee 
Changed "wrong command" to "unintended command".

**Comment by mattheuslee** [comment]
Should our command name be search or find? I realise find seems to work better grammatically.

**Review by mattheuslee — APPROVED** [review]
Looks good to me

**Comment by ChuaPingChan** [comment]
I'm equally fine with both 'find' and 'search'. Can you give one example where 'find' works better grammatically?

**Comment by mattheuslee** [comment]
It's just a small thing, but "find code submission" seems to feel more natural compared to "search code submission" where is seems like it should be "search (for) code submission" in order to be closer to typing a sentence. How does @kevinLamKB and @akd13 feel about this?

**Comment by ChuaPingChan** [comment]
I see. Yes 'find' seems to be closer to typing a grammatically correct sentence. Let's see what the rest thinks.

**Review by kevinLamKB — APPROVED** [review]

**Comment by kevinLamKB** [comment]
need to note that currently addressbook4 is using find, we need to update userdocs and all the naming conventions in the app if we go with search.

so maybe find is the better option here

**Comment by mattheuslee** [comment]
okay let's change it back to find

**Comment by ChuaPingChan** [comment]
@CS2103JUN2017-T2/developers 
Okay I'll change 'search' to 'find'.

**Pull request merged**
