### PR TITLE
V0.0 Dash

### PR DESCRIPTION
**Pull request by akd13**
Merge dev guide

### CODE REVIEW

**Comment by ChuaPingChan** [comment]
@akd13 
Some of the back-quotes in the first column of the User Stories section are not inserted correctly.

**Comment by akd13** [comment]
@ChuaPingChan fixed back-quotes

**Comment by mattheuslee** [comment]
Do you still need this PR? If not we can close it.

**Comment by mattheuslee** [comment]
Closing since the other PR has been made.

**Pull request closed without merging**
